### PR TITLE
ADD: kamp-grep script (interactive grep) 

### PR DESCRIPTION
**Pull request by jtrv**
A script to grep with ripgrep and fzf interactively, and open the file in a new buffer with the cursor at the selected result's line/column.

note: I branched from update-readme to avoid the need of a third PR for the changes to README.md regarding kamp-grep

### CODE REVIEW

**Comment by vbauerster** [comment]
Hey, thanks for contribution!
I noticed there is some `kcr edit` in the actual script :)

**Comment by jtrv** [comment]
🤦🏽 Good catch @vbauerster ! Looks like I was moving too quickly. I assumed because it worked on my system that it was good to go. Just fixed it and tested it after swapping `kamp` for `kcr`, looks like it should be good now 👍🏽

**Comment by jtrv** [comment]
sorry to make so many changes, I decided to clean up the format of the script so it is more readable

**Comment by vbauerster** [comment]
I found that line highlighting is buggy, for example searching for `proxy` in this code base doesn't highlight:
Screen Shot 2022-04-01 at 13 24 13

Is it same on your system?

**Pull request merged**
